{"reExports":[],"name":"Effect.Exception.Unsafe","comments":null,"declarations":[{"children":[],"comments":"Throw an exception in pure code. This function should be used very\nsparingly, as it can cause unexpected crashes at runtime.\n","title":"unsafeThrowException","info":{"declType":"value","type":{"annotation":[],"tag":"ForAll","contents":["a",{"annotation":[],"tag":"TypeApp","contents":[{"annotation":[],"tag":"TypeApp","contents":[{"annotation":[],"tag":"TypeConstructor","contents":[["Prim"],"Function"]},{"annotation":[],"tag":"TypeConstructor","contents":[["Effect","Exception"],"Error"]}]},{"annotation":[],"tag":"TypeVar","contents":"a"}]},null]}},"sourceSpan":{"start":[9,1],"name":".spago/exceptions/v4.0.0/src/Effect/Exception/Unsafe.purs","end":[9,45]}},{"children":[],"comments":"Defined as `unsafeThrowException <<< error`.\n","title":"unsafeThrow","info":{"declType":"value","type":{"annotation":[],"tag":"ForAll","contents":["a",{"annotation":[],"tag":"TypeApp","contents":[{"annotation":[],"tag":"TypeApp","contents":[{"annotation":[],"tag":"TypeConstructor","contents":[["Prim"],"Function"]},{"annotation":[],"tag":"TypeConstructor","contents":[["Prim"],"String"]}]},{"annotation":[],"tag":"TypeVar","contents":"a"}]},null]}},"sourceSpan":{"start":[13,1],"name":".spago/exceptions/v4.0.0/src/Effect/Exception/Unsafe.purs","end":[13,37]}}]}